### PR TITLE
[JENKINS-31221] Resolved issue - Implement access to comments count

### PR DESCRIPTION
**Pull request by Safe0**
Ticket:
https://issues.jenkins-ci.org/browse/JENKINS-31221?jql=issuetype%20%3D%20Improvement%20AND%20text%20~%20sloccount

### CODE REVIEW

**Comment by mixalturek** [comment]
Thank you for the pull request, I will look at it during this weekend.

**Comment by Safe0** [comment]
Thanks!

**Comment by Safe0** [comment]
add POV users changes in description ticket

**Comment by mixalturek** [comment]
Comments count is displayed only in files.jelly. I'm missing the same changes in SloccountResult/folders.jelly, SloccountResult/languages.jelly, SloccountResult/modules.jelly, SloccountTablePortlet/table.jelly, SloccountBuildAction/statistics.jelly and maybe other places. Keyword for searching in the sources is probably "${%Lines}".

**Comment by mixalturek** [comment]
And SloccountDiff should probably contain comments count too. Please search all "lineCount" and "getLineCount" and decide if it is also relevant there or not.

**Comment by Safe0** [comment]
Ok I did all the changes I will do further tests on my production server when I can before updating the pull request here

**Comment by Safe0** [comment]
I pushed the changes:

[JENKINS-31221] Resolved issue - Implement access to comments count

add commentCount:
SloccountDiff.java
SloccountDiffLanguage.java
SloccountDiffSummary.java

add column in jelly:
statistics.jelly
languages.jelly
modules.jelly

SloccountParser: in parseLine remove commentCount and replace in report.add commentCount by 0

**Comment by Safe0** [comment]
Thanks!

**Pull request merged**
