### PR TITLE
[NO_MERGE] [JENKINS-55620] hardcode jaxb dependencies

### PR DESCRIPTION
**Pull request by batmat**
Based on #52.

Deemed to fix [JENKINS-55620](https://issues.jenkins-ci.org/browse/JENKINS-55620)

cc @jenkinsci/java11-support

### CODE REVIEW

**Comment by batmat** [comment]
@jglick Also, interested by a look from you Jesse given you provided feedback in [JENKINS-51965](https://issues.jenkins-ci.org/browse/JENKINS-51965).

**Comment by oleg-nenashev** [comment]
@batmat could you please mark it as "NO_MERGE" for now? Even if we go forward with such approach, I would expect the libs to be shipped by an API plugin

**Comment by batmat** [comment]
So I tried to use https://github.com/jenkinsci/jaxb-plugin instead and it works too on jdk11.

Going to double-check later because I have to go AFK now, but thought I'd post a quick update already.

**Comment by jglick** [comment]
> it works too

Make sure you run in a realistic class loading environment, not `JenkinsRule` nor `hpi:run`: actually install `*.jpi` from here in a regular Jenkins server.

**Comment by batmat** [comment]
@jglick sorry should have been more specific: I did a fully manual test. So it is *actually* _working_ from an end user standpoint.

**Comment by batmat** [comment]
@jglick yes, that was my plan. I was waiting for https://github.com/jenkins-infra/repository-permissions-updater/pull/999 to be merged to use an Incremental release, but I'm going to push a change showing it with a timestamped SNAPSHOT in the meantime.

**Comment by batmat** [comment]
Just force pushed after rebasing to allow the creation on an Incremental release.
This worked as: https://repo.jenkins-ci.org/incrementals/hudson/plugins/sloccount/sloccount/1.25-rc223.f76d173e4f2d/sloccount-1.25-rc223.f76d173e4f2d.hpi

**Comment by batmat** [comment]
https://github.com/batmat/jaxb-java11-demo to try this easily

**Comment by oleg-nenashev** [comment]
Would be nice to integrate #54 into this PR so that we get building with Java 11 in place

**Comment by batmat** [comment]
@oleg-nenashev given I don't have commit permission, it will anyway be unused until merged.

**Comment by oleg-nenashev** [comment]
@batmat it makes sense to fix the title now. It does not longer hardcode deps, and it likely can be merged

**Comment by oleg-nenashev** [comment]
We also need a `java11-compatibility` JIRA ticket for this issue, I believe

**Comment by batmat** [comment]
Despite my testing says that it should work anyway, I'm going to close this, at least for now, given JAXB is a detached plugin in Jenkins Core 2.164+ on Java 11.

**Pull request closed without merging**
